sudo: false
language: node_js
node_js:
- '4'
install:
- npm install
script:
- npm run precommit
deploy:
  provider: heroku
  api_key:
    secure: 134bf008-8e37-471d-8b3c-1d1e0509e10d
  on: master
  app: dream-team-4
