sudo: false
language: node_js
node_js:
- '4'
install:
- npm install
script:
- npm run precommit
deploy:
  provider: heroku
  api_key:
    secure: Ut7dtkyyOMdp7bagp/bnrjU9uIx/ZuRDIbwaClqFl/itNTAmJAlmFSNEKKfL7V1II36jVSMLpTzJj82gQswQg+IQ8YhBHloYoaY/TwQ6hm6jFnUrJPiIlnupzYaZkGOw6hQJRl0mK4m87lQFa6a+lNSmqHbKrAbiOhYKUpIJx5+Yw1ZoYzKtC02ZyiQdNTDh9/rtUVYSfxP0XJA/Z76hIKzUHTRyKC3iLVz5r4oK3jATdJsjh24HTVhbssVilV3M7yeYJv9useTCu/roWDaTG8lsgyHBfFWhWKQjuxtDRgTlsBGKyJH6T9u0G3647t07F/TMcv7FKiWbqgw2gTy1KJnLzGq/xv7teXaMyXxdCDJ8kokuqKyfrO2QGBsZhhrfVAQN4gVPU90UnvqPTBoOUKbXrpsHIJ/56SMsL/vI3iWDpz8Mr+XUpL9sdiszE8s8JUxEGuTvVC8bVLno6H2gUDuGYByJoakl4JgD1zlFFYk0IKLdWZt/0IlsRrCDpWEgAdi1l9to1R+MtzFUY28SsNTgRaoSsYArafZAfmQaopUbvytWUFCUQ+dXjvT5u8ayy1V0t2rs1VkRl0kFBFhmfrL7aqN1xBvibEE39Vc6wOquksDPjDLZwPZocwQ0BcRBbrHFb3DSnWJLiW7uH4aMWd3GeWzqlrQs59m7hg+75Vs=
  on: master
  app: dream-team-4
